SELECT 
e.id as id,
e.venue_id as venue_id,
e.event_name as event_name,
trim(e.bx_event_link) as event_link,
trim(e.event_image) as event_image,
e.event_desc as event_description,
e.event_date_start as event_date,
e.event_price as event_price,
trim(e.purchase_link) as event_purchase_link,
v.name as venue_name,
v.phone as venue_phone,
v.twitter as venue_twitter,
v.facebook_id as venue_facebook_id,
v.facebook_username as venue_facebook_username,
 trim(v.url) as venue_url,
v.city as venue_city,
v.country as venue_country,
v.formatted_address as venue_formatted_address,
v.facebook_username as venue_facebook_username,
v.fs_tags as venue_foursquare_tags,
v.fs_rating as venue_foursquare_rating,
v.fs_rating_signals as venue_foursquare_rating_signals,
v.address as venue_address,
v.lat as venue_latitude,
v.lon as venue_longitude,
v.bx_tag as venue_biletix_tag,
 trim( v.bx_url) as venue_biletix_url,
v.bx_name as venue_biletix_name,
 trim('http://www.biletix.com'||v.bx_image) as venue_biletix_image,
v.bx_desc as venue_biletix_description,
v.bx_directions as venue_biletix_directions
 FROM event e INNER JOIN venue v ON (e.venue_id = v.id)
where e.event_date_start BETWEEN $1 and $2
ORDER BY e.event_date_start